Repository BattleCh1cken/notebookinator, pull requests merged in 2024-02, with the labels that each got.

#5 :sparkles: Linear theme
  docs.pdf
  docs.typ
  internals.typ
  lib.typ
  themes/linear/colors.typ
  themes/linear/components/components.typ
  themes/linear/components/decision-matrix.typ
  themes/linear/components/glossary.typ
  themes/linear/components/pro-con.typ
  themes/linear/components/toc.typ
  themes/linear/entries.typ
  themes/linear/entry-types.typ
  themes/linear/format.typ
  themes/linear/linear.typ
  themes/linear/rules.typ
  themes/themes.typ
Labels: type:enhancement, semver:minor

#17 :sparkles: Tweaks to the Radial theme
  docs.typ
  entries.typ
  themes/radial/components/code-blocks.typ
  themes/radial/components/components.typ
  themes/radial/components/headings.typ
  themes/radial/components/label.typ
  themes/radial/components/team.typ
  themes/radial/components/toc.typ
  themes/radial/entries.typ
  themes/radial/format.typ
  themes/radial/radial.typ
  themes/radial/rules.typ
  utils.typ
Labels: type:enhancement, semver:minor

#20 📝 Add a gallery to the README
  .github/workflows/ci.yml
  .gitignore
  README.md
  gallery/linear-03.png
  gallery/linear-04.png
  gallery/linear-05.png
  gallery/linear.typ
  gallery/radial-4.png
  gallery/radial-5.png
  gallery/radial-6.png
  gallery/radial.typ
  justfile
  themes/linear/entries.typ
  themes/radial/components/gantt-chart.typ
Labels: type:documentation

#22 :sparkles: Add some missing features to the default theme
  themes/default/components.typ
  themes/default/default.typ
Labels: type:enhancement, semver:minor

#25 ⚡ Linear title margins
  themes/linear/entries.typ
  themes/linear/format.typ
  themes/linear/linear.typ
Labels: type:enhancement, help wanted
